namespace Helium.Network.Api.Vanilla.V15;

/// <summary>
/// Stores all <see cref="StatisticCategories.Custom"/> statistics used by the vanilla protocol.
/// To translate those into minecraft's ID names, convert them to snake case and prepend <c>minecraft.</c>
/// </summary>
public enum CustomStatistics
{
	LeaveGame,
	PlayOneMinute,
	TimeSinceDeath,
	SneakTime,
	WalkOneCm,
	CrouchOneCm,
	SprintOneCm,
	SwimOneCm,
	FallOneCm,
	ClimbOneCm,
	FlyOneCm,
	DiveOneCm,
	MinecartOneCm,
	BoatOneCm,
	PigOneCm,
	HorseOneCm,
	AviateOneCm,
	Jump,
	Drop,
	DamageDealt,
	DamageTaken,
	Deaths,
	MobKills,
	AnimalsBred,
	PlayerKills,
	FishCaught,
	TalkedToVillager,
	TradedWithVillager,
	EatCakeSlice,
	FillCauldron,
	UseCauldron,
	CleanArmor,
	CleanBanner,
	InteractWithBrewingstand,
	InteractWithBeacon,
	InspectDropper,
	InspectHopper,
	InspectDispenser,
	PlayNoteblock,
	TuneNoteblock,
	PotFlower,
	TriggerTrappedChest,
	OpenEnderchest,
	EnchantItem,
	PlayRecord,
	InteractWithFurnace,
	InteractWithCraftingTable,
	OpenChest,
	SleepInBed,
	OpenShulkerBox
}
